version: '3.8'

services:
  asterisk:
    image: asterisk/asterisk:latest
    restart: always
    ports:
      - 5060:5060/udp
      - 10000-10010:10000-10010/udp
    volumes:
      - ./asterisk-config:/etc/asterisk
      - ./asterisk-logs:/var/log/asterisk

volumes:
  asterisk-config:
  asterisk-logs:

